#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
gEQDSK + statefile to input.profiles
====================================
This example shows how OMAS can be used to generate a GACODE input.profiles
file given a gEQDSK file and a ONETWO statefile.
"""

from __future__ import print_function, division, unicode_literals

from matplotlib import pyplot
from omas import *

from omfit.classes.omfit_eqdsk import OMFITgeqdsk
from omfit.classes.omfit_onetwo import OMFITstatefile
from omfit.classes.omfit_gacode import OMFITgacode

gfilename = '/Users/meneghini/tmp/ONETWO_files/g0.03000' # gEQDSK file
sfilename = '/Users/meneghini/tmp/ONETWO_files/statefile_3.000000E+00.nc' #ONETWO statefile
ipfilename = '/Users/meneghini/tmp/ONETWO_files/input.profiles' #input.profiles generated with PROFILES_GEN

# load OMFIT classes
gEQDSK = OMFITgeqdsk(gfilename)
statefile = OMFITstatefile(sfilename)
ip = OMFITgacode(ipfilename)

# equilibrium ods from gEQDSK (and fluxSurfaces)
ods = gEQDSK.to_omas()

# append core profiles and sources based on ONETWO statefile
ods = statefile.to_omas(ods)

# generate new input.profiles file
open(ipfilename+'2','w').close()
ip1 = OMFITgacode(ipfilename+'2',GACODEtype='profiles').from_omas(ods)

# compare the input.profiles file generated by PROFILES_GEN and the one generated via OMFIT+OMAS
ip1.plot()
ip.plot()
pyplot.show()
