name: Regression no -m unittest

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip github]')"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install numpy
      run: |
        python3 -m pip install numpy

    - name: Install dependencies
      run: |
        python3 -m pip install -r requirements.txt

    - name: Install OMAS
      run: |
        python3 -m pip install .[machine]

    - name: Move to root and try importing OMAS
      run: |
        cd /
        python3 -c "import omas; print(omas.__version__)"

    - name: Run OMAS tests
      run: |
        make test_no_munittest
