name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # Do not mark issues with these labels
        exempt-issue-labels: "bug,enhancement,WIP"
        stale-issue-message: >
            This issue has not seen any activity in the past 60 days.
            It is now marked as stale and will be closed in 7 days if
            no further activity is registered.
        # Do not mark PRs with these labels
        exempt-pr-labels: 'WIP,Blocked-by-other-PR'
        stale-pr-message: >
            This PR has not seen any activity in the past 60 days.
            It is now marked as stale and will be closed in 7 days if
            no further activity is registered.
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 60
        days-before-close: 21
